// <auto-generated />
namespace Sample_Project_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateEmployeeColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateEmployeeColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "202007170246177_updateEmployeeColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
